name: Custom_Deploy

on:
  push:
    branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

jobs:
  build:
    name: Build
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.*

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build
      - name: show files
        run: ls
    
      - name: Upload Build file
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: dist
          
      - name: Deploy APP to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
